"""Add delivery and conversation models

Revision ID: 38a5a14052f8
Revises: 20250213_summaries
Create Date: 2026-02-14 11:03:28.576753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38a5a14052f8'
down_revision: Union[str, None] = '20250213_summaries'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_post_id'), 'conversations', ['post_id'], unique=False)
    op.create_index(op.f('ix_conversations_started_at'), 'conversations', ['started_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('reaction', sa.String(length=10), nullable=True),
    sa.Column('delivered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_batch_id'), 'deliveries', ['batch_id'], unique=False)
    op.create_index(op.f('ix_deliveries_delivered_at'), 'deliveries', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_deliveries_post_id'), 'deliveries', ['post_id'], unique=False)
    op.create_index(op.f('ix_deliveries_user_id'), 'deliveries', ['user_id'], unique=False)
    op.alter_column('agent_calls', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'success'::character varying"))
    op.drop_index('ix_agent_calls_created_at', table_name='agent_calls')
    op.drop_index('ix_summaries_post_user', table_name='summaries')
    op.alter_column('user_token_usage', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_token_usage', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_token_usage', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_token_usage', 'cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('user_token_usage', 'request_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_user_token_usage_user_id_date', table_name='user_token_usage')
    op.drop_constraint('uq_user_token_usage', 'user_token_usage', type_='unique')
    op.create_index(op.f('ix_user_token_usage_user_id'), 'user_token_usage', ['user_id'], unique=False)
    op.add_column('users', sa.Column('delivery_style', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_delivered_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('users', 'memory_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('users', 'memory_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'last_delivered_at')
    op.drop_column('users', 'delivery_style')
    op.drop_index(op.f('ix_user_token_usage_user_id'), table_name='user_token_usage')
    op.create_unique_constraint('uq_user_token_usage', 'user_token_usage', ['user_id', 'date', 'model'])
    op.create_index('ix_user_token_usage_user_id_date', 'user_token_usage', ['user_id', 'date'], unique=False)
    op.alter_column('user_token_usage', 'request_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_token_usage', 'cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('user_token_usage', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_token_usage', 'output_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_token_usage', 'input_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index('ix_summaries_post_user', 'summaries', ['post_id', 'user_id'], unique=False)
    op.create_index('ix_agent_calls_created_at', 'agent_calls', ['created_at'], unique=False)
    op.alter_column('agent_calls', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'success'::character varying"))
    op.drop_index(op.f('ix_deliveries_user_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_post_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_delivered_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_batch_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_started_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_post_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
