"""create posts table with crawl tracking

Revision ID: 7be4bb0d3cdd
Revises: 
Create Date: 2026-02-13 17:57:44.259580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be4bb0d3cdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hn_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('collected_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_dead', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('has_html', sa.Boolean(), nullable=True),
    sa.Column('has_text', sa.Boolean(), nullable=True),
    sa.Column('has_markdown', sa.Boolean(), nullable=True),
    sa.Column('is_crawl_success', sa.Boolean(), nullable=True),
    sa.Column('crawl_retry_count', sa.Integer(), nullable=True),
    sa.Column('crawl_error', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summarized_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_hn_id'), 'posts', ['hn_id'], unique=True)
    op.create_index(op.f('ix_posts_score'), 'posts', ['score'], unique=False)
    op.create_index(op.f('ix_posts_type'), 'posts', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_type'), table_name='posts')
    op.drop_index(op.f('ix_posts_score'), table_name='posts')
    op.drop_index(op.f('ix_posts_hn_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
