"""add_foreign_keys_to_all_tables

Revision ID: aa19fc4f688a
Revises: ca002ecaabd2
Create Date: 2026-02-15 22:07:17.092139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa19fc4f688a'
down_revision: Union[str, None] = 'ca002ecaabd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_user_created'), table_name='summaries')
    op.drop_constraint(op.f('uq_summaries_post_user_type'), 'summaries', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_summaries_post_user_type'), 'summaries', ['post_id', 'user_id', 'prompt_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_summaries_user_created'), 'summaries', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
